spring:
  application:
    name: onlineStore



  datasource:
    url: jdbc:mysql://localhost:3306/onlineStore?createDatabaseIfNotExist=true
    username: root
    password: Root12Init@

  #Data base properties data source definition (SQL server)
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect



#Data base properties data source definition (SQL server)

#  datasource:
#    url: jdbc:mysql://localhost:3306/onlineStore?createDatabaseIfNotExist=true
#    username: root
#    password: Root12Init@
#    driver-class-name: com.mysql.jdbc.Driver
#
#
#  jpa:
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#    generate-ddl: true
#    hibernate:
#     ddl-auto: create
  #  properties:
  #   hibernate:
  #     dialect: org.hibernate.dialect.MySQLDialect
